apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:29-apache
        env:
        - name: MYSQL_HOST
          value: nextcloud-mysql-service:3306
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-secret
              key: mysql-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nc.alejandrohj.es"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: OVERWRITEHOST
          value: "nc.alejandrohj.es"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc
