apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
type: Opaque
stringData:
  mysql-root-password: "nextcloudrootpassword"
  mysql-database: "nextcloud"
  mysql-user: "nextclouduser"
  mysql-password: "nextcloudpassword"
